name: notes
description: Basic Flutter App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  sizer: ^2.0.15
  firebase_storage: ^10.3.7
  firebase_messaging: ^13.0.0
  firebase_app_check: ^0.0.7
  firebase_performance: ^0.8.2+4
  firebase_analytics: ^9.3.3
  firebase_in_app_messaging: ^0.6.0+23
  cloud_firestore: ^3.4.6
  firebase_crashlytics: ^2.8.9
  getwidget: ^3.0.1
  flutter_bloc: ^8.1.1
  dartdoc: ^6.0.1
  dartz: ^0.10.1
  uuid: 3.0.6
  injectable: 1.5.3
  auto_route: ^5.0.1
  google_sign_in: ^5.4.1
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2
  equatable: ^2.0.5
  cloud_firestore_odm: ^1.0.0-dev.28
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  easy_localization: ^3.0.1
  fl_chart: ^0.55.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.4
  build_runner:
  auto_route_generator: ^5.0.2
  freezed: ^2.1.0+1
  cloud_firestore_odm_generator: ^1.0.0-dev.28
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  # to be able to read from app_config.json
  assets:
    - config/
    - assets/
    - lang/